### ISSUE TITLE
(Classes) Query_Builder_* - The name of title is in conflict with the CSS.

### ISSUE THREAD

**Issue by indigofeather** [fuel/docs#420]
``` javascript
/home/lance/docs/assets/js/combined.js:
  179       list.push('<a href="#/'+$(this).attr('id')+'">'+prefix+$(this).text().split('(')[0]+"()</a>");
  180   });
  181:  $('footer').append('<div id="methods"><a href="#" id="methods_handle">method list</a><div id="method_list">'+list.join('')+'</div></div>');
  182   $('#methods_handle').click(function(e){
  183       e.preventDefault();
```

``` html
/home/lance/docs/classes/database/qb_delete.html:
   57           </p>
   58  
   59:          <h2 id="methods">Methods</h2>
   60  
   61           <article>

/home/lance/docs/classes/database/qb_insert.html:
   57           </p>
   58  
   59:          <h2 id="methods">Methods</h2>
   60  
   61           <article>

/home/lance/docs/classes/database/qb_select.html:
   54           </p>
   55  
   56:          <h2 id="methods">Methods</h2>
   57  
   58           <article>

/home/lance/docs/classes/database/qb_update.html:
   55           </p>
   56  
   57:          <h2 id="methods">Methods</h2>
   58  
   59           <article>

/home/lance/docs/classes/database/qb_where.html:
   64           </p>
   65  
   66:          <h3 id="methods">Methods</h3>
   67  
   68           <article>
```

``` css
/home/lance/docs/assets/css/combined.css:
#methods{
    width: 200px;
    height: 100%;
    position: absolute;
    top: 0px;
    right: 0px;
}
```
